import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import cn from "@acme/utils/cn";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-screen bg-white antialiased",
          montserrat.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
